apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prom2teams.fullname" . }}
  labels:
    {{- include "prom2teams.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "prom2teams.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prom2teams.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "prom2teams.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /opt/prom2teams/helmconfig/
          env:
          - name: APP_CONFIG_FILE
            value: {{ .Values.prom2teams.config | quote }}
          - name: PROM2TEAMS_PORT
            value: {{ .Values.prom2teams.port | quote }}
          - name: PROM2TEAMS_HOST
            value: {{ .Values.prom2teams.host | quote }}
          - name: PROM2TEAMS_CONNECTOR
            value: {{ .Values.prom2teams.connector | quote }}
          - name: PROM2TEAMS_GROUP_ALERTS_BY
            value: {{ .Values.prom2teams.group_alerts_by | quote }}
          - name: PROM2TEAMS_LOGLEVEL
            value: {{ .Values.prom2teams.loglevel }}
          {{- range $key, $value := .Values.prom2teams.extraEnv }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.securityContext.enabled }}
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- if .Values.securityContext.enabled }}
      securityContext:
        runAsNonRoot: {{ if eq (int .Values.securityContext.runAsUser) 0 }}false{{ else }}true{{ end }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
    {{- end }}

