apiVersion: v1
kind: Service
metadata:
  name: {{ include "prom2teams.fullname" . }}
  labels:
{{ include "prom2teams.labels" . | indent 4 }}
{{ include "prom2teams.labels" . | indent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8089
      protocol: TCP
      name: http
  selector:
    {{- include "prom2teams.selectorLabels" . | nindent 4 }}
