name: Build Docker and Push
on:
#  push:
#    branches:
#      - master
#  pull_request:
#    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Build Docker
#    if: ${{ github.repository == 'idealista/prom2teams' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag prom2teams:$(date +%s)

#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          file: ./Dockerfile
#          platforms: linux/amd64
#          push: false
#          tags: ebini/prom2teams:latest